Require activesupport kernel extentions for specs
Resolves multiple errors of specs

```
NoMethodError:
    undefined method `suppress' for #<RSpec::ExampleGroups::WhileExecutingStrategy::Processing::WhenSimultaneousJobControlsTheRuntimeLock::WhenOnConflictLogGiven:0x00005600b03bb670>
    Did you mean?  super
```